### ISSUE TITLE
instructions unclear at the end

### ISSUE THREAD

**Issue by makeopts** [Icy-Thought/snowflake#21]
Hello, I was trying to setup your dots on NixOS unstable but I keep having trouble with the ending command, It says
> After completing your setup, there remains one command to be executed (device = folder name of your device placed inside hosts, which in this case is X:

when in the command, the device is never mentioned, I could just be dumb, and I don't know if this is the place for help, but I don't know where else to put it.

I also might be stupid to say that when running the command, it throws me this error;
```
error: syntax error, unexpected end of file

       at /nix/store/iwxphjd3klhhvprixy5qf2vz4nhdbic1-source/modules/networking/wgConnect/akkadianVPN.nix:1:1:

<̙{c3ȚOZR8hг,f<.uઢ/OezՕH,gտKRrHG\6@p;Z?_hR?iؓpȉEf6Rv0[p3SVn$[Α5c$#8;왆ǤU!m)8ř_YΨQ0 A7aO'K d,b
                                                                                                        | ^
            2| 3drS9Ȱ3f)ɞ+=xjb~_Hv?z)h	Btagl'h]uoG7;UVuH)0Eըa=Ht" &4Zhf[:qv幛_V/h!k2gIi:6\x&8p"R$6ċ.kôa|\GjN|, bޫQmNHR|rml^
                                                                                                                           q<H%Sr@>o=W6ZF.Z|s;Ff	&Oqr1+eFĂK/ܝT<\b\yeolž5!bv3J쿲 L{IU;
                                                                                                                                                                                            5HU^(3oE-*|vXNtmɺ|RYf.]"TeX_pѐSf6.L,
```
I ran `nix-collect-garbage` but it still gave me this error and to be honest, I'm completely out of ideas

**Comment by Icy-Thought** [comment]
Make sure to remove `modules/networking/wgConnect` from the repository and rebuild.

That folder is intended for my personal usage. Will make sure to update the `README.md` later today.

**Comment by Icy-Thought** [comment]
Should be fixed now! If you find any other issues that require clarification, do not hesitate to ask for help! :)

Link to change: https://github.com/Icy-Thought/snowflake#remove-wgconnect-directory

Closing this issue with the assumption that it has been solved. If not, re-open it! Good luck! :smile:
