### ISSUE TITLE
Installing Nix-Flake System section needs an update (maybe)

### ISSUE THREAD

**Issue by HassanYA** [Icy-Thought/snowflake#25]
Hello
Many thanks for sharing your amazing setup. I want to try it out. I cannot help but get confused by the "Installing Nix-Flake System" section. I think either the command or the text is incorrect.

**Comment by Icy-Thought** [comment]
It is outdated indeed, I need to revise it at some point. Hopefully I can do that this weekend otherwise the week after. Nonetheless, you can always comment here and I will try to help you out! :blush:

**Comment by Icy-Thought** [comment]
I had some spare time to rewrite bits of the `README.md`. (more to come)

Any suggestions that you reckon I should add to the installation section?

**Comment by HassanYA** [comment]
Thanks. I'll go through the entire thing Sunday or Monday. I am a newbie to nix and ricing in general. I'll be sure to leave feedback if necessary.

**Comment by HassanYA** [comment]
Hello again. So I followed the steps except for hiding files from file managers. I did one additional step to add a label to ext4 partition.

when i run:
`nixos-rebuild switch --use-remote-sudo --flake .#conf-name --impure`

I get the following message:
`error: flake 'git+file:///home/hasan/Workspace/public/snowflake?shallow=1' does not provide attribute 'packages.x86_64-linux.nixosConfigurations."conf-name".config.system.build.nixos-rebuild', 'legacyPackages.x86_64-linux.nixosConfigurations."conf-name".config.system.build.nixos-rebuild' or 'nixosConfigurations."conf-name".config.system.build.nixos-rebuild'`

I executed this command on my ~/Workspace/public/snowflake . I do not know if that made a difference. I do not know where to place DEVICE-X in `nixos-rebuild switch --use-remote-sudo --flake .#conf-name --impure`

can you please help

**Comment by Icy-Thought** [comment]
I need to clarify that part, `DEVICE-X` is the name you choose as a hostname for your device and then you replace the conf-name bit with that name (the DEVICE-X)

**Comment by HassanYA** [comment]
I have executed the below, more or less it's the same error :(
```
[nix-shell:~/Workspace/public/snowflake]$ sudo nixos-rebuild switch --flake .#hasan --impure
warning: Git tree '/home/hasan/Workspace/public/snowflake' is dirty
error: flake 'git+file:///home/hasan/Workspace/public/snowflake?shallow=1' does not provide attribute 'packages.x86_64-linux.nixosConfigurations."hasan".config.system.build.nixos-rebuild', 'legacyPackages.x86_64-linux.nixosConfigurations."hasan".config.system.build.nixos-rebuild' or 'nixosConfigurations."hasan".config.system.build.nixos-rebuild'
```

**Comment by HassanYA** [comment]
I can add my stuff into a remote repo if you'd like. maybe i made a mistake

**Comment by icefishii** [comment]
Getting the exact same error as @HassanYA moved the stuff to hosts/laptop and ran sudo nixos-rebuild switch --flake .#laptop --impure  even checked again if i was in the right folder

**Comment by Icy-Thought** [comment]
Going to replicate the setup in tomorrow and try to document + respond with the proper answer. Apologies y'all.

**Comment by icefishii** [comment]
No worries, if u need someone to test it again just @ me here

**Comment by HassanYA** [comment]
Inside 
~/Workspace/public/snowflake/hosts/hasan

**Comment by Icy-Thought** [comment]
Try `git add ./hosts/hasan/*` from snowflake repo then `nixos-rebuild switch --use-remote-sudo --flake .#hasan --impure`

**Comment by Icy-Thought** [comment]
@icefishii if you have some spare time, please try the above suggestion too and report back if it fixed the issue. :)

**Comment by icefishii** [comment]
okii, will try it when I get home tonight

**Comment by icefishii** [comment]
that worked! tried it in a vm and it went smooth this time :)

**Comment by HassanYA** [comment]
for me, it did a bunch of copying then failed with below. Unlike @icefishii, I am not using a VM

`$ sudo nixos-rebuild switch --flake .#hasan --impure`

```
error:
       … while calling the 'seq' builtin

         at /nix/store/lwyjz70qh12nq6cb7fixl85vryzxqm3c-source/lib/modules.nix:322:18:

          321|         options = checked options;
          322|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          323|         _module = checked (config._module);

       … while calling the 'throw' builtin

         at /nix/store/lwyjz70qh12nq6cb7fixl85vryzxqm3c-source/lib/modules.nix:298:18:

          297|                     ''
          298|             else throw baseMsg
             |                  ^
          299|         else null;

       error: The option `modules.desktop.extensions.player' does not exist. Definition values:
       - In `/nix/store/lwyjz70qh12nq6cb7fixl85vryzxqm3c-source/flake.nix':
           {
             music = {
               enable = true;
             };
             video = {
           ...
```

**Comment by icefishii** [comment]
you'll need to change up some stuff in the config  I think it was in the default.nix under ./hosts/xyz

**Comment by icefishii** [comment]
cause the module it's referencing doesn't exist

**Comment by Icy-Thought** [comment]
Finally, thanks for confirming it and happy nixing @icefishii !!! xD

@HassanYA, `modules.desktop.extensions.player` is actually `modules.desktop.toolset.player` and I am to blame for that issue.. forgot to update the structure of the template. Apologies..

**Comment by Icy-Thought** [comment]
Also, I don't know if you read the `hardware.nix` file or not, but make sure to enable/disable the other CPU configuration setting!

**Comment by HassanYA** [comment]
I am using /etc/hardware-configuration.nix so I should
Ran following commands
`$ git reset head --hard`
`$ git pull`
`$ cp -r templates/hosts/desktop hosts/hasan`
`$ cp /etc/nixos/hardware-configuration.nix hosts/hasan/hardware.nix`
`$ git add .`
`$ nixos-rebuild switch --use-remote-sudo --flake .#hasan --impure`

I get this output:
```
trace: warning: The option `services.gnome.chrome-gnome-shell.enable' defined in `/nix/store/3pzj0xnxy8jzmqkpnm0lvzz7la3x315k-source' has been renamed to `services.gnome.gnome-browser-connector.enable'.
error: builder for '/nix/store/ylwd5hpl30gnkn9izj1xhp18r8q58nir-user-units.drv' failed with exit code 1;
       last 1 log lines:
       > ln: failed to create symbolic link '/nix/store/q7bqggcchzcncg6663xcx3vs6j4gjj2g-user-units/xdg-desktop-portal-gtk.service': File exists
       For full logs, run 'nix log /nix/store/ylwd5hpl30gnkn9izj1xhp18r8q58nir-user-units.drv'.
error: 1 dependencies of derivation '/nix/store/fpsk5i922g6h5zz3d6d9y9wf7kgb5p70-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/86q74qi9vi7r8mawdbmr80qn4h7ywgkj-nixos-system-hasan-24.05.20240229.1536926.drv' failed to build
```

Sorry for the bother

**Comment by Icy-Thought** [comment]
What you do when you have similar errors is grep for the complaint and disable/enable or replace with newer setting version found in the [nixos option](https://search.nixos.org/options) site.

As you can see, this time it complained about `services.gnome.chrome-gnome-shell.enable` was renamed to `services.gnome.gnome-browser-connector.enable`. You can just replace it where defined with your option. (will update repo soon)

**Comment by Icy-Thought** [comment]
Also, the `hardware.nix` file in your `hosts/hassan` (or whatever you choose to name your host device) will override `hardware-configuration.nix`. Therefore you ought to copy and paste the necessary bits into that file before you proceed with the installation.

**Comment by Icy-Thought** [comment]
Let's go!!! :rocket: 

No worries, happy to help!
